### ISSUE TITLE
streaming output issue

### ISSUE THREAD

**Issue by Elijah-0616** [sazonovanton/SirChatalot#8] opened 2023-12-05 09:39 UTC
Hello, developer, is it possible to achieve streaming output for this project using the Telegram [editMessageText](https://core.telegram.org/bots/api#editmessagetext) and the OpenAI [Streaming](https://platform.openai.com/docs/api-reference/streaming) APIs? If so, that would be so cool.
thanks :)

**Comment by sazonovanton** [comment] 2023-12-14 06:42
Hey there!
Originally, I wasn't planning on implementing streaming messages through constant editing, as it seems a bit clunky, and in regular conversations with people, we receive a complete message, not a continuous output. However, I'll look into the possibility of implementing it, but it hasn't been a priority just yet :)

**Comment by Elijah-0616** [comment] 2023-12-14 15:04
Okay, thanks for the reply. BTW, I found a bug, or maybe it's feature? when you send one message, the bot replies with two. However, I seem to have found a solution. If you change the `if` to `elif` on this line of code, it works fine.
:)
https://github.com/sazonovanton/SirChatalot/blob/6d098d901f5cfd7ad3561ee67a7f3497d7bdb61c/main.py#L382
https://github.com/sazonovanton/SirChatalot/blob/6d098d901f5cfd7ad3561ee67a7f3497d7bdb61c/main.py#L393

**Comment by sazonovanton** [comment] 2023-12-15 09:01
Thanks, great catch with the bug you mentioned! I thought that I have pushed fix for that.
Now it should work as intended

**Closed as not planned** 2024-02-06 09:14 UTC

**Comment by kithawk** [comment] 2024-07-09 13:11
@sazonovanton would it be possible to add streaming response as an option in config file? It would allow for quicker reading on longer messages. Typical implementations make use of editing the message after 100 characters to avoid rate limiting

**Comment by sazonovanton** [comment] 2024-07-16 16:53
> @sazonovanton would it be possible to add streaming response as an option in config file? It would allow for quicker reading on longer messages. Typical implementations make use of editing the message after 100 characters to avoid rate limiting

I have been asked that. Adding this feature may require some code refactoring. First, I plan to maybe add a /regenerate command and implement a check to see if the output was incomplete adding a continue button.
